defmodule Increase.Files do
  @moduledoc """
  Files are objects that represent a file hosted on Increase's servers. The file
  may have been uploaded by you (for example, when uploading a check image) or it
  may have been created by Increase (for example, an autogenerated statement PDF).
  If you need to download a File, create a File Link.

  See https://increase.com/documentation/api/files for the full API
  reference for this resource.
  """

  alias Increase.Client
  alias Increase.Page

  defmodule File do
    @moduledoc """
    Files are objects that represent a file hosted on Increase's servers. The
    file may have been uploaded by you (for example, when uploading a check
    image) or it may have been created by Increase (for example, an
    autogenerated statement PDF). If you need to download a File, create a File
    Link.

    ## Fields

      * `id` - The File's identifier.
      * `created_at` - The time the File was created.
      * `description` - A description of the File.
      * `direction` - Whether the File was generated by Increase or by you and sent to Increase.
      * `filename` - The filename that was provided upon upload or generated by Increase.
      * `idempotency_key` - The idempotency key you chose for this object. This value is unique
        across Increase and is used to ensure that a request is only
        processed once. Learn more about
        [idempotency](https://increase.com/documentation/idempotency-keys).
      * `mime_type` - The MIME type of the file.
      * `purpose` - What the File will be used for. We may add additional possible values for
        this enum over time; your application should be able to handle such
        additions gracefully.
      * `type` - A constant representing the object's type. For this resource it will always be
        `file`.
    """

    defstruct [
      :id,
      :created_at,
      :description,
      :direction,
      :filename,
      :idempotency_key,
      :mime_type,
      :purpose,
      :type
    ]

    @type t :: %__MODULE__{
            id: String.t(),
            created_at: DateTime.t(),
            description: String.t() | nil,
            direction: String.t(),
            filename: String.t() | nil,
            idempotency_key: String.t() | nil,
            mime_type: String.t(),
            purpose: String.t(),
            type: String.t()
          }

    @doc false
    @spec decode(map()) :: t()
    def decode(raw) when is_map(raw) do
      %__MODULE__{
        id: raw["id"],
        created_at: Increase.Decode.datetime(raw["created_at"]),
        description: raw["description"],
        direction: raw["direction"],
        filename: raw["filename"],
        idempotency_key: raw["idempotency_key"],
        mime_type: raw["mime_type"],
        purpose: raw["purpose"],
        type: raw["type"]
      }
    end
  end

  @doc """
  To upload a file to Increase, you'll need to send a request of Content-Type
  `multipart/form-data`. The request should contain the file you would like to
  upload, as well as the parameters for creating a file.

  `POST /files`
  """
  @spec create(Increase.Client.t() | keyword() | nil, map() | keyword(), keyword()) ::
          {:ok, File.t()} | {:error, Increase.Error.t()}
  def create(client, params \\ %{}, opts \\ []) do
    client = Client.resolve(client)

    path = "/files"
    idempotency_key = Keyword.get(opts, :idempotency_key)

    case Client.request(client, :post, path,
           body: Map.new(params),
           idempotency_key: idempotency_key
         ) do
      {:ok, body} -> {:ok, File.decode(body)}
      {:error, error} -> {:error, error}
    end
  end

  @doc """
  Retrieve a File

  `GET /files/{file_id}`
  """
  @spec retrieve(Increase.Client.t() | keyword() | nil, String.t(), keyword()) ::
          {:ok, File.t()} | {:error, Increase.Error.t()}
  def retrieve(client, file_id, opts \\ []) do
    client = Client.resolve(client)

    path = "/files/#{file_id}"
    idempotency_key = Keyword.get(opts, :idempotency_key)

    case Client.request(client, :get, path, idempotency_key: idempotency_key) do
      {:ok, body} -> {:ok, File.decode(body)}
      {:error, error} -> {:error, error}
    end
  end

  @doc """
  List Files

  Returns a `%Increase.Page{}` whose `data` is a list of `%__MODULE__.
  File{}` structs. Page through results with
  `Increase.Page.auto_paging_stream/1` or `Increase.Page.auto_paging_each/2`.

  `GET /files`
  """
  @spec list(Increase.Client.t() | keyword() | nil, map() | keyword(), keyword()) ::
          {:ok, Page.t()} | {:error, Increase.Error.t()}
  def list(client, params \\ %{}, opts \\ []) do
    client = Client.resolve(client)

    path = "/files"
    query = Map.new(params)

    fetch_next = fn cursor ->
      list(client, Map.put(query, :cursor, cursor), opts)
    end

    case Client.request(client, :get, path, query: query) do
      {:ok, body} -> {:ok, Page.new(body, fetch_next, &File.decode/1)}
      {:error, error} -> {:error, error}
    end
  end
end
